import { useParams } from 'react-router-dom'
import { CalendarDays, CheckCircle2, FileUp, Timer } from 'lucide-react'
import { PageShell } from '../components/PageShell'
import { Button, SkeletonList } from '../components/ui'
import { usePageView } from '../hooks/usePageView'
import { useEffect, useState } from 'react'
import { getPlatformData } from '../services/platformService'

function getAssignmentStatus(deadline: string, rawStatus: string) { const due = new Date(`${deadline}T00:00:00`); const today = new Date(); today.setHours(0, 0, 0, 0); if (due < today) return 'Closed'; return ['Graded', 'Submitted', 'Draft'].includes(rawStatus) ? rawStatus : 'Open' }
export function AssignmentPage() { const { id } = useParams(); usePageView('Assignment'); const platformData = getPlatformData(); const assignment = platformData.assignments.find((item) => item.id === id); const [loading, setLoading] = useState(false); useEffect(() => { const t = setTimeout(() => setLoading(false), 450); return () => clearTimeout(t) }, [id]); if (!assignment) return <PageShell title="Assignment not found" subtitle="The requested assignment is unavailable." />; const status = getAssignmentStatus(assignment.deadline, assignment.status); const submissionClosed = status === 'Closed'
  return <PageShell title="Assignments" subtitle="Bring your learning to life through thoughtful practice.">{loading ? <SkeletonList count={2} lines={2} /> : <><section className="assignment-hero"><div><span className={`assignment-state ${submissionClosed ? 'closed' : ''}`}>{status}</span><h2>{assignment.title}</h2><p>{assignment.instructions}</p></div><div className="assignment-deadline"><CalendarDays size={22} /><span>Deadline<strong>{new Date(`${assignment.deadline}T00:00:00`).toLocaleDateString('en', { month: 'long', day: 'numeric' })}</strong></span></div></section><div className="assignment-layout"><section className="assignment-brief"><p className="eyebrow">Your challenge</p><h3>Make this work your own.</h3><p>{assignment.instructions}</p><div className="assignment-tip"><Timer size={19} /><span><strong>Take your time.</strong> Review the brief, show your process, and submit only when you are proud of it.</span></div></section><section className="submission-panel"><div className="submission-heading"><div className="file-icon"><FileUp size={21} /></div><div><p className="eyebrow">Your submission</p><h3>Ready when you are</h3></div></div>{submissionClosed ? <div className="submission-closed"><CheckCircle2 size={22} /><div><strong>Submission closed</strong><p>This assignment’s deadline has passed. Your work can no longer be submitted.</p></div></div> : <><label>Submission notes<textarea rows={4} placeholder="Tell your mentor a little about your approach..." /></label><label className="upload-field">Upload your work<input type="file" /><span>Choose a file or drag it here</span></label><Button variant="primary">Submit assignment</Button></>}</section></div></>}</PageShell> }
